<a href="https://colab.research.google.com/github/blnarsaiah/GenAI_Assignments_Bronze/blob/main/Assignment_1_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
data = {
    'YearsExp': [2,5,1,8,4,10,3,6,7,2],
    'TrainHrs': [40,60,20,80,50,90,30,70,75,25],
    'WorkHrs':  [38,42,35,45,40,48,37,44,46,36],
    'NumProjects': [3,6,2,8,5,9,4,7,7,3],
    'ProdScore': [62,78,55,88,72,92,65,82,85,60]
}

# New Section

In [ ]:
df = pd.DataFrame(data)
df

   YearsExp  TrainHrs  WorkHrs  NumProjects  ProdScore
0         2        40       38            3         62
1         5        60       42            6         78
2         1        20       35            2         55
3         8        80       45            8         88
4         4        50       40            5         72
5        10        90       48            9         92
6         3        30       37            4         65
7         6        70       44            7         82
8         7        75       46            7         85
9         2        25       36            3         60

In [ ]:
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   YearsExp     10 non-null     int64
 1   TrainHrs     10 non-null     int64
 2   WorkHrs      10 non-null     int64
 3   NumProjects  10 non-null     int64
 4   ProdScore    10 non-null     int64
dtypes: int64(5)
memory usage: 532.0 bytes

YearsExp       0
TrainHrs       0
WorkHrs        0
NumProjects    0
ProdScore      0
dtype: int64

In [ ]:
X = df[['YearsExp','TrainHrs','WorkHrs','NumProjects']]
y = df['ProdScore']
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
model = LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [ ]:
print("Feature Coefficients:")
coefficients = pd.Series(model.coef_, index=X.columns)
coefficients

Feature Coefficients:

YearsExp      -0.263658
TrainHrs       0.272684
WorkHrs       -1.085511
NumProjects    4.885986
dtype: float64